### ISSUE TITLE
2015级程设/第三次上机/最小非负值/题号/53

### ISSUE THREAD

**Issue by rty1121310520** [GoatGirl98/Walkthrough-of-ACCoding-in-BUAA#1]
思路写错了，不是“稍微推一推就能发现 1 2 5都只能到1，其他的全都能推到0”

if(n == 1 || n == 2) printf("1\n");
else printf("0\n");

**Comment by rty1121310520** [comment]
思路没说清楚1 2 5是指什么

**Comment by GoatGirl98** [comment]
已修正，感谢提醒。
