### ISSUE TITLE
2016级-软件学院-C++程序设计/C12-2016级C++期末上机模拟赛/F-王助教大炼钢铁

### ISSUE THREAD

**Issue by Ledenel** [GoatGirl98/Walkthrough-of-ACCoding-in-BUAA#3]
您好，我是本题作者。不敲的原因是任何时候敲了立即变成碳含量不足的熟铁，本题不能加碳，变成熟铁就完蛋了，所以只能慢慢烧完。可能是本题表述不够清楚，或者本人公式推导有误，恳请批评指正。

**Comment by GoatGirl98** [comment]
您好，经过您对题目的补充说明，以及对题目的重新推导之后，将会上传新的题解。如果我对该补充说明的理解无误的话（也就是碳含量一旦严格小于t%即为熟铁，意味着此次炼钢失败），则公式推导是无误的。感谢您对题目的补充说明以及对题解的贡献！

**Comment by Ledenel** [comment]
您好，您的理解无误。另外，钢的定义在题目中已经写明，不是碳含量小于等于t%，而是碳含量等于t%。虽然根据公式解出将生铁炼成钢需要负数时间显然不合理，不能作为答案，然而当碳含量小于t%的情况，根据不同的诠释方式（开放世界诠释与封闭世界诠释），确实认为是钢和不是钢都是合理的，即本题在解出炼钢时间<0时直接输出0也是一种合理的理解。本题原本的设计思路是将熟铁失败的情况隐藏在题目描述中，因表述不清造成的诸多麻烦特在此致歉。
