### ISSUE TITLE
2016级-软件学院-C++程序设计/C7-2016级C++第七次上机/B-王助教掷骰子

### ISSUE THREAD

**Issue by Ledenel** [GoatGirl98/Walkthrough-of-ACCoding-in-BUAA#4]
您好，我是本题作者。本题当时在设计之时并未考虑考察矩阵快速幂相关知识，而是考察常识和灵机一动。
常识为，一个六面均匀骰子在滚足够多次后，每个面朝上的概率应当相等。
灵机一动的部分为，本题只要求保留两位小数，所以k足够大的时候就可以大胆输出六个面均等的答案了。
本题需要在本机自己编造数据进行测试，测试k**至少**为多大时输出六个面均等。实际上又不超时又能正确的k的范围相当大，上机时随意试验几次就可以得到答案。

**Comment by Ledenel** [comment]
transition_matrix = np.full((6,6), fill_value=0.25)
display(transition_matrix)
for left, right in [[1,6],[2,5],[3,4]]:
    left -= 1
    right -= 1
    transition_matrix[left][left] = 0
    transition_matrix[right][right] = 0
    transition_matrix[left][right] = 0
    transition_matrix[right][left] = 0
display(transition_matrix)

**Comment by Ledenel** [comment]
另，本题的推导证明过程不是非常严谨，正在重新推导中

**Comment by GoatGirl98** [comment]
您好，该解法将会添加到现有项目中，并附带证明。该结论用矩阵幂以及该概率转移矩阵的特征值去证明即可。感谢您对题解的贡献！
