### ISSUE TITLE
关于22级信息类程序设计基础 

### ISSUE THREAD

**Issue by Toby-Shi-cloud** [GoatGirl98/Walkthrough-of-ACCoding-in-BUAA#5]
22级信息类程序设计基础 不仅试题已经不再对外公布 连gitee仓库也没有了 题解和题面也只在课程群里有发。另外现在北航accoding网址搬迁了，从accoding.cn改到了accoding.buaa.edu.cn，但是目测网站没有发生任何变化。

**Comment by GoatGirl98** [comment]
感谢反馈。第一个消息我之前就知道了。第二个是因为之前输入accoding.cn会直接跳转至新网址accoding.buaa.edu.cn，故一直没有更新。现在已进行更新。
