### ISSUE TITLE
寻求出题合作

### ISSUE THREAD

**Issue by specialzxw** [GoatGirl98/Walkthrough-of-ACCoding-in-BUAA#6]
hello，这里是蓝桥云课（[www.lanqiao.cn](http://www.lanqiao.cn/)），冒昧通过GitHub联系，我们看到您常常分享oj题目的AC代码，所以我们想邀请您合作。我们平台平台近期计划为蓝桥杯备赛题库（[https://www.lanqiao.cn/problems/?first_category_id=1&sort=students_count](http://https//www.lanqiao.cn/problems/?first_category_id=1&sort=students_count)）中新增一批 oj 题，现对外招募【竞赛教练/有获奖经验的同学】参加出题，会有酬劳的！我们想邀请您参与，如果您近期时间充裕，有兴趣尝试，欢迎填写表单 [https://lanqiao-courses.feishu.cn/share/base/form/shrcng7A6oOJRhMAFpRSEcBbbhh](http://https//lanqiao-courses.feishu.cn/share/base/form/shrcng7A6oOJRhMAFpRSEcBbbhh) 报名，我们 24 小时内将会通过微信私聊给报名的 老师/同学 发送出题资料，进行 1 道题目的试写。

**Comment by GoatGirl98** [comment]
不好意思，暂无合作想法，非常感谢您的关注。
